services:
  db:
    image: postgres:17
    restart: unless-stopped
    container_name: letsenroll-db
    env_file: ./config/.env
    ports:
      - "127.0.0.1:5430:5432" # So we can connect to it using an SSH tunnel via localhost:5430
    networks:
      - letsenroll
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
  api:
    image: letsenroll-api:latest
    restart: unless-stopped
    container_name: letsenroll-api
    networks:
      - letsenroll
      - caddy
    volumes:
      - type: bind
        source: ./config
        target: /config
      - type: bind
        source: ./logs
        target: /logs
  bot:
    image: letsenroll-bot:latest
    restart: unless-stopped
    container_name: letsenroll-bot
    networks:
      - letsenroll
    volumes:
      - type: bind
        source: ./config
        target: /config
      - type: bind
        source: ./logs
        target: /logs

networks:
  letsenroll: {}
  caddy:
    external: true

volumes:
  db-data: