services:
  db:
    image: postgres:17
    restart: unless-stopped
    container_name: letsenroll-db
    env_file: ./config/.env
    networks:
      - letsenroll
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
  api:
    image: letsenroll-api:latest
    restart: unless-stopped
    container_name: letsenroll-api
    networks:
      - letsenroll
      - caddy
    volumes:
      - type: bind
        source: ./config
        target: /config
      - type: bind
        source: ./logs
        target: /logs
  bot:
    image: letsenroll-bot:latest
    restart: unless-stopped
    container_name: letsenroll-bot
    networks:
      - letsenroll
    volumes:
      - type: bind
        source: ./config
        target: /config
      - type: bind
        source: ./logs
        target: /logs

networks:
  letsenroll: {}
  caddy:
    external: true

volumes:
  db-data: