spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/commandinator?currentSchema=public
    username: postgres
    password:

api:
  discord-client-id: 1234           # Optional if you don't run the website
  discord-client-secret: abcd       # Optional if you don't run the website
  front-url: http://localhost:5173  # Optional if you don't run the website